const STORAGE_KEY = "my-trainings-state-v2";
const defaults = [
 {id:"workout-a",name:"Workout A",exercises:["Hip Thrust","Leg Curl","Step Up","Pallof Press"]},
 {id:"workout-b",name:"Workout B",exercises:[]},
 {id:"workout-c",name:"Workout C",exercises:[]},
 {id:"hiking",name:"Hiking",exercises:[]},
 {id:"micro",name:"Micro Workout",exercises:[]}
].map(t=>({...t,exercises:t.exercises.map(n=>({id:crypto.randomUUID(),name:n,sets:3,reps:10,weight:0,range:"8–12"}))}));
const library=["Hip Thrust","Glute Bridge","Bulgarian Split Squat","Cable Kickback","Leg Curl","Romanian Deadlift","Nordic Curl","Step Up","Leg Press","Hack Squat","Goblet Squat","Back Squat","Walking Lunge","Pallof Press","Plank","Dead Bug","Cable Crunch","Lat Pulldown","Seated Row","Chest Press","Shoulder Press"];
let state=load(); let route={screen:"home",templateId:null};
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{templates:structuredClone(defaults),activeSession:null,history:[]}}catch{return {templates:structuredClone(defaults),activeSession:null,history:[]}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function nav(screen,extra={}){route={screen,templateId:null,...extra};render();scrollTo(0,0)}
function tpl(){return state.templates.find(t=>t.id===route.templateId)}
function header(t,back){return `<div class="header"><div>${back?`<button class="ghost" data-action="${back}">← Zpět</button>`:""}<h1>${t}</h1></div></div>`}
function home(){return `${header("My Trainings")}<div class="stack">${state.templates.map(t=>`<div class="template-card"><button class="template-main" data-open="${t.id}"><span><strong>${t.name}</strong><span class="small muted">${t.exercises.length} cviků</span></span><span>›</span></button><button class="template-edit" data-edit="${t.id}">Upravit</button></div>`).join("")}</div><div class="nav"><button class="secondary" data-action="history">Historie</button><button class="secondary" data-action="settings">Nastavení</button></div>`}
function prep(){const t=tpl();return `${header(t.name,"home")}${t.exercises.length?`<div class="card"><ul class="exercise-list">${t.exercises.map(e=>`<li class="exercise-row"><div><strong>${e.name}</strong><div class="small muted">${e.sets} × ${e.range}</div></div></li>`).join("")}</ul></div><div class="actions"><button class="primary" data-start="${t.id}">Začít trénink</button><button class="secondary" data-edit="${t.id}">Upravit šablonu</button></div>`:`<div class="notice">Šablona je prázdná.</div><button class="primary" data-edit="${t.id}">Přidat cviky</button>`}`}
function editor(){const t=tpl();return `${header(t.name,"home")}<p class="muted">Cviky uložené tady zůstanou v šabloně i pro příště.</p><button class="primary" data-action="library">+ Přidat cvik</button><div class="stack" style="margin-top:12px">${t.exercises.length?t.exercises.map((e,i)=>`<div class="card editable-exercise"><div class="exercise-title"><div><div class="small muted">${i+1}. cvik</div><h3>${e.name}</h3><div class="small muted">${e.sets} × ${e.range}</div></div></div><div class="editor-actions"><button class="mini-button" data-up="${e.id}" ${i===0?"disabled":""}>↑</button><button class="mini-button" data-down="${e.id}" ${i===t.exercises.length-1?"disabled":""}>↓</button><button class="mini-button danger-text" data-remove="${e.id}">Smazat</button></div></div>`).join(""):`<div class="card muted">Zatím žádný cvik.</div>`}</div><div class="actions"><button class="secondary" data-open="${t.id}">Hotovo</button></div>`}
function lib(){return `${header("Přidat cvik","editor")}<div class="card"><input id="search" class="text-input" type="search" placeholder="Hledat cvik"></div><div id="results" class="stack" style="margin-top:12px">${library.map(n=>`<button class="workout-button" data-add="${n}"><strong>${n}</strong><span>+</span></button>`).join("")}</div>`}
function start(id){const t=state.templates.find(x=>x.id===id);state.activeSession={id:crypto.randomUUID(),workoutName:t.name,startedAt:new Date().toISOString(),currentIndex:0,exercises:t.exercises.map((e,i)=>({id:crypto.randomUUID(),name:e.name,status:i?"waiting":"active",sets:Array.from({length:e.sets},(_,j)=>({id:crypto.randomUUID(),position:j,weight:e.weight,reps:e.reps,completed:false}))}))};save();nav("workout")}
function workout(){const s=state.activeSession;if(!s)return home();const e=s.exercises[s.currentIndex];if(!e)return finish();return `${header(s.workoutName)}<button class="ghost" data-action="overview">${s.currentIndex+1} / ${s.exercises.length} · Přehled</button><div class="card"><h2>${e.name}</h2>${e.sets.map(set=>`<div class="set-row"><strong>${set.position+1}.</strong><input type="number" step="0.5" value="${set.weight}" data-field="weight" data-set="${set.id}"><input type="number" value="${set.reps}" data-field="reps" data-set="${set.id}"><button class="check ${set.completed?"done":""}" data-complete="${set.id}">${set.completed?"✓":""}</button></div>`).join("")}</div><div class="actions"><button class="secondary" data-action="postpone">Přeskočit prozatím</button><button class="ghost" data-action="home">Zavřít a uložit</button></div>`}
function next(){const s=state.activeSession;let i=s.exercises.findIndex((e,j)=>j!==s.currentIndex&&e.status==="waiting");if(i<0)i=s.exercises.findIndex(e=>e.status==="postponed");if(i<0){nav("finish");return}s.currentIndex=i;s.exercises[i].status="active"}
function overview(){const s=state.activeSession;return `${header(s.workoutName,"workout")}<div class="card">${s.exercises.map((e,i)=>`<button class="workout-button flat" data-jump="${i}"><span>${e.status==="completed"?"✓":e.status==="postponed"?"⏭":i===s.currentIndex?"▶":"○"} ${e.name}</span><span>›</span></button>`).join("")}</div>`}
function finish(){const s=state.activeSession;return `${header("Dokončení","workout")}<div class="card"><h3>${s.workoutName}</h3><p class="muted">${s.exercises.filter(e=>e.status==="completed").length}/${s.exercises.length} cviků dokončeno</p></div><button class="primary" data-action="finish">Dokončit trénink</button>`}
function history(){return `${header("Historie","home")}${state.history.length?state.history.map(s=>`<div class="card history-item"><strong>${s.workoutName}</strong><div class="small muted">${new Date(s.completedAt).toLocaleString("cs-CZ")}</div></div>`).join(""):`<div class="card muted">Zatím žádný dokončený trénink.</div>`}`}
function settings(){return `${header("Nastavení","home")}<div class="card"><p class="muted">Data jsou uložená pouze v tomto Safari.</p><button class="danger" data-action="reset">Smazat všechna data</button></div>`}
function render(){document.querySelector("#app").innerHTML=({home,prep,editor,lib,workout,overview,finish,history,settings}[route.screen]||home)();bind()}
function bind(){document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>nav("prep",{templateId:b.dataset.open}));document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>nav("editor",{templateId:b.dataset.edit}));document.querySelectorAll("[data-start]").forEach(b=>b.onclick=()=>start(b.dataset.start));document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>{tpl().exercises.push({id:crypto.randomUUID(),name:b.dataset.add,sets:3,reps:10,weight:0,range:"8–12"});save();nav("editor",{templateId:route.templateId})});document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{if(confirm("Smazat cvik ze šablony?")){const t=tpl();t.exercises=t.exercises.filter(e=>e.id!==b.dataset.remove);save();render()}});document.querySelectorAll("[data-up]").forEach(b=>b.onclick=()=>move(b.dataset.up,-1));document.querySelectorAll("[data-down]").forEach(b=>b.onclick=()=>move(b.dataset.down,1));document.querySelectorAll("[data-complete]").forEach(b=>b.onclick=()=>{const s=state.activeSession,e=s.exercises[s.currentIndex],set=e.sets.find(x=>x.id===b.dataset.complete);set.completed=!set.completed;if(e.sets.every(x=>x.completed)){e.status="completed";next()}save();render()});document.querySelectorAll("input[data-field]").forEach(i=>i.onchange=()=>{const e=state.activeSession.exercises[state.activeSession.currentIndex],set=e.sets.find(x=>x.id===i.dataset.set);set[i.dataset.field]=Number(i.value);save()});document.querySelectorAll("[data-jump]").forEach(b=>b.onclick=()=>{state.activeSession.currentIndex=Number(b.dataset.jump);state.activeSession.exercises[Number(b.dataset.jump)].status="active";save();nav("workout")});const q=document.querySelector("#search");if(q)q.oninput=()=>document.querySelectorAll("[data-add]").forEach(b=>b.style.display=b.dataset.add.toLowerCase().includes(q.value.toLowerCase())?"":"none");document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==="home")nav("home");if(a==="editor")nav("editor",{templateId:route.templateId});if(a==="library")nav("lib",{templateId:route.templateId});if(a==="workout")nav("workout");if(a==="overview")nav("overview");if(a==="postpone"){state.activeSession.exercises[state.activeSession.currentIndex].status="postponed";next();save();render()}if(a==="finish"){state.activeSession.completedAt=new Date().toISOString();state.history.unshift(state.activeSession);state.activeSession=null;save();nav("history")}if(a==="history")nav("history");if(a==="settings")nav("settings");if(a==="reset"&&confirm("Smazat všechna data?")){state={templates:structuredClone(defaults),activeSession:null,history:[]};save();nav("home")}})}
function move(id,d){const t=tpl(),i=t.exercises.findIndex(e=>e.id===id),j=i+d;if(j<0||j>=t.exercises.length)return;[t.exercises[i],t.exercises[j]]=[t.exercises[j],t.exercises[i]];save();render()}
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));render();